spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/nanda?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: India@123
    driverClassName: com.mysql.jdbc.Driver
    
test.message: what are you doing

#security:
#  oauth2:
#    client:
#      client-id: cliente
#      client-secret: password
#      scope: read,write
#      auto-approve-scopes: '.*'    